---
abstract: 'a set of version requirements for a CPAN dist'
author:
  - 'Ricardo Signes <rjbs@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Version-Requirements
requires:
  Test::More: 0.88
resources:
  repository: git://git.codesimply.com/Version-Requirements.git
version: 0.100630
